-- The existing MIC tenant needs an explicit portal destination before its
-- company-login action can be enabled.  The HumanSoft SSO code itself is
-- generated by HumanSoft per login, so it is intentionally not stored here.
UPDATE "Company"
SET "portalUrl" = 'https://micorganize.humansoft.co.th/welcome'
WHERE "companyCode" = 'MIC'
  AND "deletedAt" IS NULL
  AND "portalUrl" IS NULL;
